In [33]:
import pandas as pd
import numpy as np
import plotly.express as px
import tensorflow as tf

path = '/home/z/Downloads/label/'
filepath = 'test.csv'
df = pd.read_csv(path + filepath)


In [54]:
df = df[['device_field03', 'illuminance_onoff', 'device_data_reg_dtm']]
print(df)

       device_field03  illuminance_onoff  device_data_reg_dtm
0                19.0                  0  2020-07-01 00:01:05
1                19.0                  0  2020-07-01 00:11:06
2                19.0                  0  2020-07-01 00:21:06
3                19.0                  0  2020-07-01 00:31:06
4                19.0                  0  2020-07-01 00:41:05
...               ...                ...                  ...
48979            16.0                  1  2021-06-30 23:10:43
48980            16.0                  1  2021-06-30 23:20:42
48981            15.0                  1  2021-06-30 23:30:42
48982            15.0                  1  2021-06-30 23:40:42
48983            16.0                  1  2021-06-30 23:50:43

[48984 rows x 3 columns]


In [51]:
# df['device_data_reg_dtm'] = pd,to_datetime(df['device_data_reg_dtm'], infer_datetime_format=True)
train_test = df['device_field03'].to_numpy()
label = df['illuminance_onoff'].to_numpy()
datetime_data = df['device_data_reg_dtm']

In [50]:
print(train_test[:10])
print(label[:10])
print(datetime_data)

[19. 19. 19. 19. 19. 17. 17. 19. 19.  0.]
[0 0 0 0 0 0 0 0 0 0]
<bound method Series.to_timestamp of 0        2020-07-01 00:01:05
1        2020-07-01 00:11:06
2        2020-07-01 00:21:06
3        2020-07-01 00:31:06
4        2020-07-01 00:41:05
                ...         
48979    2021-06-30 23:10:43
48980    2021-06-30 23:20:42
48981    2021-06-30 23:30:42
48982    2021-06-30 23:40:42
48983    2021-06-30 23:50:43
Name: device_data_reg_dtm, Length: 48984, dtype: object>


In [49]:
print(train_test.shape)
print(label_data.shape)

(48984,)
(48984,)


In [43]:
train_test = train_test / 255.0
train_test[:10]

array([0.0002922 , 0.0002922 , 0.0002922 , 0.0002922 , 0.0002922 ,
       0.00026144, 0.00026144, 0.0002922 , 0.0002922 , 0.        ])

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(1,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])